apiVersion: v1
kind: Service
metadata:
  namespace: shorturl-dev
  name: admin
  labels:
    app: admin
    service: admin
spec:
  ports:
  - port: 5003
    name: http
  selector:
    app: admin

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: shorturl-dev
  name: admin-v1
  labels:
    app: admin
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: admin
      version: v1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: admin
        version: v1
    spec:
      containers:
      - name: admin
        image: shorturl/managementgui:dev
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 5003
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Kubernetes

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: shorturl-dev
  name: admin
spec:
  hosts:
  - "*"
  gateways:
  - shorturl-gateway
  http:
  - match:
    - uri:
        prefix: /admin
    route:
    - destination:
        host: admin
        port:
          number: 5003