# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  system.debug: true

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        buildContext: '$(Build.SourcesDirectory)'
        dockerfile: 'ShortUrl.IdentityServer/Dockerfile'
        tags: 'dogtail9/shorturl:$(build.buildnumber)'

    - task: Docker@2
      displayName: Push an image
      inputs:
        containerRegistry: 'Docker Hub'
        repository: 'shorturl'
        command: 'push'
        tags: 'dogtail9/shorturl:$(build.buildnumber)'