version: '3.4'

services:
  shorturl.identityserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5999:80"

  shorturl.managementgui:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5002:80"

  shorturl.redirectapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "5000:80"

  shorturl.urlmanagementapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:80"

  shorturl.data:
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd
    ports:
      - "1433:1433"

  shorturl.cache:
    image: shorturl/cache:v0.1
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd
    ports:
      - "1434:1433"

  shorturl.zipkin:
    image: openzipkin/zipkin-slim
    ports:
      - "9411:9411"