version: '3.4'

services:
  shorturl.identityserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IDENTITY_ISSUER=http://shorturl.identityserver
      - ManagementGuiUrl=http://shorturl:5003
    ports:
      - "5000:5000"

  shorturl.managementgui:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - IDENTITY_AUTHORITY=http://shorturl:5000/sts
    ports:
      - "5003:5003"

  shorturl.redirectapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "5001:5001"

  shorturl.urlmanagementapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - IDENTITY_AUTHORITY=http://shorturl:5000/sts
    ports:
      - "5002:5002"

  shorturl.data:
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd
    ports:
      - "1433:1433"

  shorturl.cache:
    image: shorturl/cache:v0.1
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd
    ports:
      - "1434:1433"

  shorturl.zipkin:
    image: openzipkin/zipkin-slim
    ports:
      - "9411:9411"